<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ListMesinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timestamp = Carbon::now()->toDateString();
        $mesin = array(
            array('code' => '01 IMD 06', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 IMD 07', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 KOK 24', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 KOK 25', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 MEI 32', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 MEI 33', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 REP 01', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 REP 02', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 01', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 02', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 07', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 08', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 09', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 14', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 15', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 16', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 17', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 18', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '01 SAN 19', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 DAH 01', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 DAH 02', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 01', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 02', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 03', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 04', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 05', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 06', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 07', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 08', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 09', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 10', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 11', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 12', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 14', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 15', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 16', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 17', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 18', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 19', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 20', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 22', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 23', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 24', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 25', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 26', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 27', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 28', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 29', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 30', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 31', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 32', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 33', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 34', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 35', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 36', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 37', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 38', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 39', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 40', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 41', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 42', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 43', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 44', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 45', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 46', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 47', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 48', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 49', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 50', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 51', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 52', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 53', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 54', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 55', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 56', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 57', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 58', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 59', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 60', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 61', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 62', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 63', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 64', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 KOK 23', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 KOK 24', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 KOK 25', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 KOK 26', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 KOK 28', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 KOK 29', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 KOK 32', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 KOK 33', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MLD 01', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MLD 02', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MLD 03', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MLD 04', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MLD 05', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MLD 06', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 01', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 02', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 03', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 04', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 05', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 06', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 07', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 08', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 09', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 10', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 11', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 12', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 14', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 15', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 16', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 17', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 18', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 19', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 20', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 21', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 22', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 23', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 24', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 25', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 26', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 27', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 28', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 29', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 30', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 31', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 32', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 33', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 34', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 35', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 36', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 37', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 38', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 39', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 40', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 41', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 42', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 43', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 50', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 51', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 52', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 53', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 54', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 MVC 55', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 REP 01', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 REP 02', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 REP 03', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 REP 04', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 65', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 66', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('code' => '02 IMD 67', 'created_at' => $timestamp, 'updated_at' => $timestamp),

        );
        DB::table('list_mesins')->insert($mesin);
    }
}
