<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MesinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timestamp = Carbon::now()->toDateString();
        $mesin = array(
            array('list_mesin_id' => 1, 'name_mesin_id' => 1, 'class_mesin_id' => 1, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 2, 'name_mesin_id' => 1, 'class_mesin_id' => 1, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 3, 'name_mesin_id' => 3, 'class_mesin_id' => 3, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 4, 'name_mesin_id' => 3, 'class_mesin_id' => 3, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 5, 'name_mesin_id' => 5, 'class_mesin_id' => 5, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 6, 'name_mesin_id' => 5, 'class_mesin_id' => 5, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 7, 'name_mesin_id' => 7, 'class_mesin_id' => 7, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 8, 'name_mesin_id' => 7, 'class_mesin_id' => 8, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 9, 'name_mesin_id' => 9, 'class_mesin_id' => 9, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 10, 'name_mesin_id' => 9, 'class_mesin_id' => 9, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 11, 'name_mesin_id' => 11, 'class_mesin_id' => 11, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 12, 'name_mesin_id' => 11, 'class_mesin_id' => 11, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 13, 'name_mesin_id' => 13, 'class_mesin_id' => 13, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 14, 'name_mesin_id' => 11, 'class_mesin_id' => 11, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 15, 'name_mesin_id' => 11, 'class_mesin_id' => 11, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 16, 'name_mesin_id' => 11, 'class_mesin_id' => 11, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 17, 'name_mesin_id' => 11, 'class_mesin_id' => 11, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 18, 'name_mesin_id' => 11, 'class_mesin_id' => 11, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 19, 'name_mesin_id' => 11, 'class_mesin_id' => 11, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 20, 'name_mesin_id' => 20, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 21, 'name_mesin_id' => 20, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 22, 'name_mesin_id' => 22, 'class_mesin_id' => 22, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 23, 'name_mesin_id' => 22, 'class_mesin_id' => 22, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 24, 'name_mesin_id' => 22, 'class_mesin_id' => 22, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 25, 'name_mesin_id' => 22, 'class_mesin_id' => 22, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 26, 'name_mesin_id' => 22, 'class_mesin_id' => 22, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 27, 'name_mesin_id' => 22, 'class_mesin_id' => 22, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 28, 'name_mesin_id' => 22, 'class_mesin_id' => 22, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 29, 'name_mesin_id' => 22, 'class_mesin_id' => 22, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 30, 'name_mesin_id' => 22, 'class_mesin_id' => 22, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 31, 'name_mesin_id' => 22, 'class_mesin_id' => 22, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 32, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 33, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 34, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 35, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 36, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 37, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 38, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 39, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 40, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 41, 'name_mesin_id' => 41, 'class_mesin_id' => 41, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 42, 'name_mesin_id' => 41, 'class_mesin_id' => 41, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 43, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 44, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 45, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 46, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 47, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 48, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 49, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 50, 'name_mesin_id' => 41, 'class_mesin_id' => 41, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 51, 'name_mesin_id' => 41, 'class_mesin_id' => 41, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 52, 'name_mesin_id' => 41, 'class_mesin_id' => 41, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 53, 'name_mesin_id' => 41, 'class_mesin_id' => 41, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 54, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 55, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 56, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 57, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 58, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 59, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 60, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 61, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 62, 'name_mesin_id' => 32, 'class_mesin_id' => 32, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 63, 'name_mesin_id' => 63, 'class_mesin_id' => 63, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 64, 'name_mesin_id' => 63, 'class_mesin_id' => 63, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 65, 'name_mesin_id' => 63, 'class_mesin_id' => 63, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 66, 'name_mesin_id' => 63, 'class_mesin_id' => 63, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 67, 'name_mesin_id' => 63, 'class_mesin_id' => 63, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 68, 'name_mesin_id' => 63, 'class_mesin_id' => 63, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 69, 'name_mesin_id' => 63, 'class_mesin_id' => 63, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 70, 'name_mesin_id' => 70, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 71, 'name_mesin_id' => 70, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 72, 'name_mesin_id' => 72, 'class_mesin_id' => 41, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 73, 'name_mesin_id' => 73, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 74, 'name_mesin_id' => 73, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 75, 'name_mesin_id' => 75, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 76, 'name_mesin_id' => 75, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 77, 'name_mesin_id' => 75, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 78, 'name_mesin_id' => 75, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 79, 'name_mesin_id' => 75, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 80, 'name_mesin_id' => 75, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 81, 'name_mesin_id' => 75, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 82, 'name_mesin_id' => 82, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 83, 'name_mesin_id' => 82, 'class_mesin_id' => 70, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 84, 'name_mesin_id' => 20, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 85, 'name_mesin_id' => 20, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 86, 'name_mesin_id' => 20, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 87, 'name_mesin_id' => 20, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 88, 'name_mesin_id' => 20, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 89, 'name_mesin_id' => 20, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 90, 'name_mesin_id' => 90, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 91, 'name_mesin_id' => 90, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 92, 'name_mesin_id' => 92, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 93, 'name_mesin_id' => 93, 'class_mesin_id' => 93, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 94, 'name_mesin_id' => 93, 'class_mesin_id' => 93, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 95, 'name_mesin_id' => 93, 'class_mesin_id' => 93, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 96, 'name_mesin_id' => 93, 'class_mesin_id' => 93, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 97, 'name_mesin_id' => 92, 'class_mesin_id' => 20, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 98, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 99, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 100, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 101, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 102, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 103, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 104, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 105, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 106, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 107, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 108, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 109, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 110, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 111, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 112, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 113, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 114, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 115, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 116, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 117, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 118, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 118, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 120, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 121, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 122, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 123, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 124, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 125, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 126, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 127, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 128, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 129, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 130, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 131, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 132, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 133, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 134, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 1', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 135, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 136, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 137, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 138, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 139, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 140, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 141, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 142, 'name_mesin_id' => 98, 'class_mesin_id' => 98, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 143, 'name_mesin_id' => 143, 'class_mesin_id' => 143, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 144, 'name_mesin_id' => 143, 'class_mesin_id' => 143, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 145, 'name_mesin_id' => 143, 'class_mesin_id' => 143, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 146, 'name_mesin_id' => 143, 'class_mesin_id' => 143, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 147, 'name_mesin_id' => 147, 'class_mesin_id' => 147, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 148, 'name_mesin_id' => 147, 'class_mesin_id' => 147, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 149, 'name_mesin_id' => 147, 'class_mesin_id' => 147, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 150, 'name_mesin_id' => 147, 'class_mesin_id' => 147, 'posisi' => '-', 'status' => 'Tidak Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 151, 'name_mesin_id' => 151, 'class_mesin_id' => 151, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 152, 'name_mesin_id' => 152, 'class_mesin_id' => 152, 'posisi' => 'Plant 2', 'status' => 'Aktif', 'created_at' => $timestamp, 'updated_at' => $timestamp),

        );
        DB::table('mesins')->insert($mesin);
    }
}
