<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NameMesinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timestamp = Carbon::now()->toDateString();
        $nameMesinData = array(
            array('list_mesin_id' => 1, 'name' => 'INJECTION KUEMIN 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 2, 'name' => 'INJECTION KUEMIN 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 3, 'name' => '200/300 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 4, 'name' => '200/300 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 5, 'name' => 'MEISHO', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 6, 'name' => 'MEISHO', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 7, 'name' => 'INJECTION REP 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 8, 'name' => 'INJECTION REP 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 9, 'name' => 'INJECTION SANYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 10, 'name' => 'INJECTION SANYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 11, 'name' => 'INJECTION SANYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 12, 'name' => 'INJECTION SANYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 13, 'name' => 'INJECTION MATSUDA 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 14, 'name' => 'INJECTION SANYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 15, 'name' => 'INJECTION SANYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 16, 'name' => 'INJECTION SANYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 17, 'name' => 'INJECTION SANYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 18, 'name' => 'INJECTION SANYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 19, 'name' => 'INJECTION SANYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 20, 'name' => '500 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 21, 'name' => '500 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 22, 'name' => 'INJECTION KUEMIN 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 23, 'name' => 'INJECTION KUEMIN 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 24, 'name' => 'INJECTION KUEMIN 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 25, 'name' => 'INJECTION KUEMIN 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 26, 'name' => 'INJECTION KUEMIN 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 27, 'name' => 'INJECTION KUEMIN 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 28, 'name' => 'INJECTION KUEMIN 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 29, 'name' => 'INJECTION KUEMIN 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 30, 'name' => 'INJECTION KUEMIN 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 31, 'name' => 'INJECTION KUEMIN 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 32, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 33, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 34, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 35, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 36, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 37, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 38, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 39, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 40, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 41, 'name' => 'INJECTION JINGDAY 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 42, 'name' => 'INJECTION JINGDAY 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 43, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 44, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 45, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 46, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 47, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 48, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 49, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 50, 'name' => 'INJECTION JINGDAY 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 51, 'name' => 'INJECTION JINGDAY 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 52, 'name' => 'INJECTION JINGDAY 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 53, 'name' => 'INJECTION JINGDAY 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 54, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 55, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 56, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 57, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 58, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 59, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 60, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 61, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 62, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 63, 'name' => 'INJECTION REP TUNGYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 64, 'name' => 'INJECTION REP TUNGYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 65, 'name' => 'INJECTION REP TUNGYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 66, 'name' => 'INJECTION REP TUNGYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 67, 'name' => 'INJECTION REP TUNGYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 68, 'name' => 'INJECTION REP TUNGYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 69, 'name' => 'INJECTION REP TUNGYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 70, 'name' => 'INJECTION TUNGYU', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 71, 'name' => 'INJECTION TUNGYU', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 72, 'name' => 'INJECTION JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 73, 'name' => 'INJECTION COLD RUNNER 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 74, 'name' => 'INJECTION COLD RUNNER 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 75, 'name' => 'INJECTION TUNGYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 76, 'name' => 'INJECTION TUNGYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 77, 'name' => 'INJECTION TUNGYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 78, 'name' => 'INJECTION TUNGYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 79, 'name' => 'INJECTION TUNGYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 80, 'name' => 'INJECTION TUNGYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 81, 'name' => 'INJECTION TUNGYU 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 82, 'name' => 'INJECTION TUNGYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 83, 'name' => 'INJECTION TUNGYU 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 84, 'name' => '500 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 85, 'name' => '500 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 86, 'name' => '500 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 87, 'name' => '500 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 88, 'name' => '500 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 89, 'name' => '500 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 90, 'name' => '200 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 91, 'name' => '200 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 92, 'name' => '1200 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 93, 'name' => '600 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 94, 'name' => '600 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 95, 'name' => '600 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 96, 'name' => '600 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 97, 'name' => '1200 TON', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 98, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 99, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 100, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 101, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 102, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 103, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 104, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 105, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 106, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 107, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 108, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 109, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 110, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 111, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 112, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 113, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 114, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 115, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 116, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 117, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 118, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 118, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 120, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 121, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 122, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 123, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 124, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 125, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 126, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 127, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 128, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 129, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 130, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 131, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 132, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 133, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 134, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 135, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 136, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 137, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 138, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 139, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 140, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 141, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 142, 'name' => 'VACUM JINGDAY', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 143, 'name' => 'VACUM PANSTONE', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 144, 'name' => 'VACUM PANSTONE', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 145, 'name' => 'VACUM PANSTONE', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 146, 'name' => 'VACUM PANSTONE', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 147, 'name' => 'INJECTION REP 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 148, 'name' => 'INJECTION REP 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 149, 'name' => 'INJECTION REP 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 150, 'name' => 'INJECTION REP 2000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 151, 'name' => 'INJECTION REP 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('list_mesin_id' => 152, 'name' => 'INJECTION JINGDAY 1000 CC', 'created_at' => $timestamp, 'updated_at' => $timestamp),

        );

        DB::table('name_mesins')->insert($nameMesinData);
    }
}
